### ISSUE TITLE
Moped::Node #ensure_connected when node is running fails on Ruby 1.9.2

### ISSUE THREAD

**Issue by dblock** [mongoid/moped#38]
```
Moped::Node
  #ensure_connected
    when node is running
      processes the block (FAILED - 1)
```

``` ruby

 1) Moped::Node#ensure_connected when node is running processes the block
     Failure/Error: node.command("admin", ping: 1)
     NoMethodError:
       undefined method `[]' for nil:NilClass
     # ./lib/moped/node.rb:74:in `block in command'
     # ./lib/moped/node.rb:522:in `[]'
     # ./lib/moped/node.rb:522:in `block (3 levels) in flush'
     # ./lib/moped/node.rb:521:in `map'
     # ./lib/moped/node.rb:521:in `block (2 levels) in flush'
     # ./lib/moped/node.rb:107:in `ensure_connected'
     # ./lib/moped/node.rb:517:in `block in flush'
     # ./lib/moped/node.rb:532:in `logging'
     # (eval):5:in `logging'
     # ./lib/moped/node.rb:516:in `flush'
     # ./lib/moped/node.rb:505:in `process'
     # ./lib/moped/node.rb:70:in `command'
     # ./spec/moped/node_spec.rb:16:in `block (5 levels) in <top (required)>'
     # ./lib/moped/node.rb:113:in `ensure_connected'
     # ./spec/moped/node_spec.rb:15:in `block (4 levels) in <top (required)>'
```

This causes things like `purge!` to fail under Ruby 1.9.2. Works with 1.9.2. 

Also need to add ruby 1.9.2 to travis.
